### ISSUE TITLE
inclusion in choosealicense.com tracker

### ISSUE THREAD

**Issue by boehs** [fossas/commons-clause#17]
This issue is a tracker for the commons clause license and the steps needed for it to appear on [choose a license](https://github.com/github/choosealicense.com/). and will serve as a discussion hub. This will be the first license on this list forbidding commercial use

# Steps to do so

Via [CONTRIBUTING.MD](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md)

## The license must have an SPDX identifier.

- SPDX terms: https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md
- [ ] **IS IN SPDX?**
- [x] The submitted license must not match another license already on the SPDX License List as per the SPDX matching guidelines.
- [x] Software licenses that apply only to executables and do not provide for the availability of the source code will not be included on the SPDX License List.
- [x] The license has identifiable and stable text; it is not in the midst of drafting.
- [x] The license steward, if any, is committed to not modifying after addition to the list and to versioning new versions in the future.

---

Optional, in order of importance

- [ ] The license substantially complies with one of the following open source definitions (even if not submitted for approval or these organization have not considered the license): **(none)**
  * [ ] [Open Source Definition (OSD)](https://opensource.org/osd) from the Open Source Initiative (OSI)
  * [ ] [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html) from the Free Software Foundation (FSF)
  * [ ] [Open Source Hardware Definition](https://www.oshwa.org/definition/) from the Open Source Hardware Association (OSHWA)
  * [ ] [Open Definition](http://opendefinition.org/od/2.1/en/) from the Open Knowledge Foundation
  * [ ] [Free Cultural Works definition](https://freedomdefined.org/Definition) from Freedom Defined.org
- [x] The license is structured to be generally usable by anyone. It is not specific to one project, consortium or corporation.
- [x] The license has actual, substantial use such that it is likely to be encountered. Substantial use may be demonstrated via use in many projects, or in one or a few significant projects. For new licenses, there are definitive plans for the license to be used in one or a few significant projects.
- [x] If the license does not substantively comply with one of the above open source definitions, then the license is primarily intended for free distribution of content (including, in the case of software, its source code) with limited restrictions, and meets other factors listed here.
- [ ] The license steward supports or is at least aware of and does not oppose its submission to the SPDX License List.

## The license must be listed on one of the following approved lists of licenses

This is impossible

- [ ] **IS IN ONE?**
- [ ] [List of OSI approved licenses](https://opensource.org/licenses/alphabetical) **(impossible per [Open Source Definition (OSD)](https://opensource.org/osd) from the Open Source Initiative (OSI))**
- [ ] [GNU's list of free licenses](https://www.gnu.org/licenses/license-list.en.html) (*note: the license must be listed in one of the three "free" categories*) **(impossible per [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html))**
- [ ] [Open Definition's list of conformant licenses](https://opendefinition.org/licenses/) (non-code) **(impossible per [Open Definition](http://opendefinition.org/od/2.1/en/))**

## The license must be used in at least 1,000 public repositories.

- [x] **is in >1000 repos?**
- [x] [GitHub:](https://github.com/search?q=Commons+Clause+License+Condition+filename%3ALICENSE&type=Code) 10,000

## 3 notable projects using the license must be identified

Note: Discovery of more is welcome and encouraged

- [x] **IS IN >2 notable projects?** (probably)
- [astronomer:](https://github.com/astronomer/astronomer) 333 stars
- [eredis (is notable due to its location - in RedisLabs](https://github.com/RedisLabs/eredis): 7 stars lol

# Is commons clause even a license?

... will get back to you on that

# Ok so, what do we need to do?

- [ ] Answer the question:
> Is commons clause even a license?
- [ ] add to SPDX
- [ ] Modify clause two: `The license must be listed on one of the following approved lists of licenses`
- [ ] Discover 1 more notable projects using it
- [ ] Obtain permission to include in SPDX (not blocking).
